<?php

/**
 * This is the model base class for the table "game_player".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GamePlayer".
 *
 * Columns in table "game_player" available as properties of the model,
 * followed by relations of table "game_player" available as properties of the model.
 *
 * @property integer $session_id
 * @property integer $game_id
 * @property integer $status
 * @property string $created
 *
 * @property Session $session
 * @property Game $game
 */
abstract class BaseGamePlayer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_player';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GamePlayer|GamePlayers', $n);
	}

	public static function representingColumn() {
		return 'token';
	}

	public function rules() {
		return array(
			array('username, session_id, game_id, token, created', 'required'),
			array('session_id, game_id, status', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>32),
			array('token', 'length', 'max'=>128),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('username, session_id, game_id, status, token, created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'session' => array(self::BELONGS_TO, 'Session', 'session_id'),
			'game' => array(self::BELONGS_TO, 'Game', 'game_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'username' => Yii::t('app', 'Username'),
			'session_id' => null,
			'game_id' => null,
			'status' => Yii::t('app', 'Status'),
			'token' => Yii::t('app', 'Token'),
			'created' => Yii::t('app', 'Created'),
			'session' => null,
			'game' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('username', $this->username, true);
		$criteria->compare('session_id', $this->session_id);
		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('token', $this->token, true);
		$criteria->compare('created', $this->created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->fbvStorage->get("settings.pagination_size"),
      ),
		));
	}
}